<p>Part of the problem here seems to be that Flurry error reporting is <em>leaving out</em> important information.</p>

<p>Anyhow, this is where I think the exception is coming from:</p>

<pre><code>private void deliverResults(ActivityClientRecord r, List&lt;ResultInfo&gt; results) {
    final int N = results.size();
    for (int i=0; i&lt;N; i++) {
        ResultInfo ri = results.get(i);
        try {
            if (ri.mData != null) {
                ri.mData.setExtrasClassLoader(r.activity.getClassLoader());
            }
            if (DEBUG_RESULTS) Slog.v(TAG,
                    "Delivering result to activity " + r + " : " + ri);
            r.activity.dispatchActivityResult(ri.mResultWho,
                    ri.mRequestCode, ri.mResultCode, ri.mData);
        } catch (Exception e) {
            if (!mInstrumentation.onException(r.activity, e)) {
                throw new RuntimeException(
                        "Failure delivering result " + ri + " to activity "
                        + r.intent.getComponent().toShortString()
                        + ": " + e.toString(), e);
            }
        }
    }
}
</code></pre>

<p>(This code isn't from Android 4.4.4, but this particular method is identical in the versions I looked at ...)</p>

<p>It would seem that <code>deliverResults</code> is catching some exception it got further up the stack, and wrapping / resthoring it as a <code>RuntimeException</code>.  At the point that the exception is constructed, it has a message, and <code>cause</code>.  Whatever is generating the stacktrace has removed that information, and that is going to make diagnosis hard.</p>
